// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/12/2026, 7:19:56 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/home/filmon/Sowtee/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/filmon/Sowtee/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/filmon/Sowtee/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/filmon/Sowtee/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/filmon/Sowtee/frontend/plugins/**/*.{js,ts,mjs}","/home/filmon/Sowtee/frontend/composables/**/*.{js,ts,mjs}","/home/filmon/Sowtee/frontend/utils/**/*.{js,ts,mjs}","/home/filmon/Sowtee/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/filmon/Sowtee/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/filmon/Sowtee/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/filmon/Sowtee/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;